# Events

## Get all events

GET http://localhost:8081/events

###

## Get event by id

GET http://localhost:8081/events/5f534e75-8dc7-42c4-97eb-c2fc867e3f40

###

## Create event

POST http://localhost:8080/events
Content-Type: application/json

{
    "title": "Event 1",
    "description": "Description 1",
    "date": "2024-11-17",
    "image": "https://blog.hubspot.de/hubfs/Germany/Blog_images/Optimize_Marketing%20Events%20DACH%202021.jpg"
}
